pipeline:
  docker-build-publish-prod:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: ustiuzhanin/grafana
    tags:
      - latest
    secrets: [ docker_username, docker_password ]
    when:
      branch:
      - master

  docker-build-publish-test:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: ustiuzhanin/grafana
    auto_tag: true
    secrets: [ docker_username, docker_password ]
    when:
      events:
      - tag
      branch:
        exclude:
        - master
      ref:
      - refs/tags/*

  ssh:
    image: appleboy/drone-ssh
    settings:
      host: zabbix.mci.ebc.one
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      port: 22
      script:
        - echo hello
        - id
        - ls -la

  telegram:
    image: appleboy/drone-telegram
    token:
      from_secret: telegram_token
    to:
      from_secret: telegram_id
    message: >
      {{#success build.status}}
      ✅ Build #{{build.number}} of `{{repo.name}}` succeeded.
      📝 Commit by {{commit.author}} on `{{commit.branch}}`:
      ```
      {{commit.message}}
      ```
      🌐 {{ build.link }}
      {{else}}
      ❌ Build #{{build.number}} of `{{repo.name}}` failed.
      📝 Commit by {{commit.author}} on `{{commit.branch}}`:
      ```
      {{commit.message}}
      ```
      🌐 {{ build.link }}
      {{/success}}
    when:
      status: [ success, failure ]
