pipeline:
   docker-build-publish:
     image: plugins/docker
     dockerfile: Dockerfile
     repo: ustiuzhanin/grafana
     auto_tag: true
     secrets: [ docker_username, docker_password ]
     when:
       branch: master

  telegram:
    image: appleboy/drone-telegram
    token: [ telegram_token ]
    to: [ telegram_id ]
    message: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}
    when:
      status: [ success, failure ]
