pipeline:
  # docker-build-publish:
  #   image: plugins/docker
  #   dockerfile: Dockerfile
  #   repo: ustiuzhanin/grafana
  #   auto_tag: true
  #   secrets: [ docker_username, docker_password ]
  #   when:
  #     branch: master

  telegram:
    image: appleboy/drone-telegram
    token: [ telegram_token ]
    to: [ telegram_id ]
    message: >
      {{#success build.status}}
        {{build.started}} - {{build.finished}}
        duration {{since build.started}}
        build {{build.link}}
        Good job.
        {{commit.message}} - {{commit.link}}
      {{else}}
        {{build.started}} - {{build.finished}}
        duration {{since build.started}}
        Fix me please.
        {{commit.message}} - {{commit.link}}.
      {{/success}}
